from fpdf import FPDF
import datetime
import os
import uuid

def sanitize_text(text):
    if text is None:
        return ""
    text = str(text)
    replacements = {
        '\u2014': '-', '\u2013': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...', '\u00d7': 'x',
        '\u2713': 'Yes', '\u2717': 'No', '\u2192': '->', '\u2190': '<-',
        '\u2022': '*', '\u25cf': '*', '\u25cb': 'o', '\u00b7': '.',
        '\u00b1': '+/-', '\u2264': '<=', '\u2265': '>=', '\u2248': '~',
        '\u03bc': 'u', '\u03c3': 's', '\u03c0': 'pi', '\u221e': 'inf',
        '\u20ac': 'EUR', '\u00a3': 'GBP', '\u00a5': 'JPY', '\u20b9': 'INR'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode('latin-1', errors='replace').decode('latin-1')

def fmt_num(val, fmt=".2f", default="N/A"):
    if val is None or val == "" or val == "N/A":
        return default
    try:
        return f"{float(val):{fmt}}"
    except (ValueError, TypeError):
        return str(val)

def fmt_pct(val, fmt=".1f", default="0.0%"):
    if val is None or val == "" or val == "N/A":
        return default
    try:
        return f"{float(val) * 100:{fmt}}%"
    except (ValueError, TypeError):
        return str(val)

class ForensicPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        # Colors
        self.brand_color = (26, 43, 76) # Navy Blue
        self.accent_color = (66, 133, 244) # Blue
        self.gray_bg = (245, 247, 250)
        self.gray_text = (100, 100, 100)
        self.danger_color = (220, 38, 38)
        self.success_color = (22, 163, 74)

    def cell(self, w, h=0, txt='', border=0, ln=0, align='', fill=False, link=''):
        if isinstance(txt, str):
            txt = sanitize_text(txt)
        return super().cell(w, h=h, txt=txt, border=border, ln=ln, align=align, fill=fill, link=link)

    def multi_cell(self, w, h, txt='', border=0, align='J', fill=False):
        if isinstance(txt, str):
            txt = sanitize_text(txt)
        return super().multi_cell(w, h, txt=txt, border=border, align=align, fill=fill)

    def header(self):
        # Don't draw header on the first page
        if self.page_no() == 1:
            return
            
        self.set_fill_color(*self.brand_color)
        self.rect(0, 0, 210, 8, 'F')
        
        self.set_font('Arial', 'B', 10)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 2)
        self.cell(0, 4, 'DEEPFORENSICS | CONFIDENTIAL ANALYSIS REPORT', 0, 0, 'L')
        self.set_text_color(0, 0, 0)
        self.set_y(15)

    def footer(self):
        if self.page_no() == 1:
            return
            
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(*self.gray_text)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y() - 2, 200, self.get_y() - 2)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by DeepForensics AI Meta-Classifier', 0, 0, 'C')
        self.set_text_color(0, 0, 0)

    def chapter_title(self, num, title):
        self.ln(5)
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(*self.gray_bg)
        self.set_text_color(*self.brand_color)
        self.set_draw_color(*self.brand_color)
        self.set_line_width(0.5)
        self.cell(0, 10, f'  {num}. {title}', 'L', 1, 'L', fill=True)
        self.set_line_width(0.2)
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def draw_table_row(self, col1, col2, bg_color=None, bold=False):
        self.set_font('Arial', 'B' if bold else '', 10)
        if bg_color:
            self.set_fill_color(*bg_color)
        else:
            self.set_fill_color(255, 255, 255)
            
        self.set_draw_color(220, 220, 220)
        col1_str = f"  {sanitize_text(col1)}"
        col2_str = sanitize_text(col2)
        
        if self.get_string_width(col2_str) < 70:
            self.cell(120, 8, col1_str, 'B', 0, 'L', fill=True)
            self.cell(0, 8, col2_str, 'B', 1, 'R', fill=True)
        else:
            self.cell(0, 8, col1_str, 'T,L,R', 1, 'L', fill=True)
            self.set_font('Arial', '', 9)
            self.multi_cell(0, 6, f"  {col2_str}", 'B,L,R', 'L', fill=True)

def generate_pdf_report(result_data: dict, output_path: str):
    import cv2
    
    pdf = ForensicPDF()
    pdf.add_page()

    # --- COVER PAGE ---
    pdf.set_fill_color(*pdf.brand_color)
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 15)
    pdf.cell(0, 10, "DIGITAL FORENSICS REPORT", 0, 1, 'C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, "Multi-Modal Deepfake Analysis", 0, 1, 'C')
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(55)
    
    # Metadata Box
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "REPORT METADATA", 0, 1)
    pdf.set_draw_color(*pdf.brand_color)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(3)
    
    job_id_str = str(result_data.get('job_id', uuid.uuid4())).split('-')[0].upper()
    filename_str = result_data.get('filename', 'Video/Image Archive')
    
    pdf.draw_table_row("Case ID / Job", job_id_str, pdf.gray_bg)
    pdf.draw_table_row("Analysis Date", datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'))
    pdf.draw_table_row("Target File Type", filename_str, pdf.gray_bg)
    pdf.draw_table_row("Frames Analyzed", str(result_data.get('frames_analyzed', 'N/A')))
    pdf.ln(15)

    # Executive Verdict
    score = result_data.get('overall_score', 0)
    verdict = result_data.get('verdict', 'Unknown')
    is_ai_altered = result_data.get('is_ai_altered', False) or "ALTERED" in verdict.upper()
    
    if is_ai_altered:
        verdict_color = (217, 119, 6) # Amber / Gold
    elif "FAKE" in verdict.upper() or score > 0.5:
        verdict_color = pdf.danger_color
    else:
        verdict_color = pdf.success_color
    
    pdf.set_fill_color(*verdict_color)
    pdf.rect(10, pdf.get_y(), 190, 35, 'F')
    
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 16)
    pdf.set_xy(10, pdf.get_y() + 6)
    pdf.cell(0, 10, "EXECUTIVE VERDICT", 0, 1, 'C')
    
    font_size = 20 if len(verdict) > 18 else 26
    pdf.set_font("Arial", 'B', font_size)
    pdf.cell(0, 12, verdict.upper(), 0, 1, 'C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # Optional AI Alteration Context Box
    if is_ai_altered:
        pdf.set_fill_color(254, 243, 199) # Light amber
        pdf.set_draw_color(245, 158, 11)
        pdf.rect(10, pdf.get_y(), 190, 16, 'DF')
        pdf.set_xy(12, pdf.get_y() + 2)
        pdf.set_font("Arial", 'B', 9)
        pdf.set_text_color(180, 83, 9)
        pdf.cell(0, 5, "AI RETOUCHING / ENHANCEMENT DETECTED", 0, 1)
        pdf.set_font("Arial", '', 8.5)
        pdf.set_text_color(120, 53, 15)
        details_str = result_data.get('alteration_details', 'Authentic identity verified, but localized AI generative enhancements detected.')
        pdf.cell(0, 5, sanitize_text(details_str[:125]), 0, 1)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(6)

    # Explainable AI Factors
    shap_features = result_data.get('shap_top_features', [])
    if shap_features:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "KEY ANOMALY FACTORS (EXPLAINABLE AI)", 0, 1)
        pdf.set_draw_color(*pdf.brand_color)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.set_line_width(0.2)
        pdf.ln(3)
        for i, feature in enumerate(shap_features[:4]):
            pdf.set_font("Arial", 'B', 10)
            pdf.set_text_color(*pdf.danger_color)
            pdf.cell(8, 8, "!", 0, 0, 'C')
            
            if "FAKE" in feature.upper() or "AUTHENTIC" in feature.upper():
                try:
                    desc, result = feature.rsplit('(', 1)
                    pdf.set_text_color(0, 0, 0)
                    pdf.set_font("Arial", '', 10)
                    pdf.cell(pdf.get_string_width(sanitize_text(desc)) + 2, 8, sanitize_text(desc), 0, 0)
                    
                    if "FAKE" in result.upper():
                        pdf.set_text_color(*pdf.danger_color)
                    else:
                        pdf.set_text_color(*pdf.success_color)
                        
                    pdf.set_font("Arial", 'B', 10)
                    pdf.cell(0, 8, f"({sanitize_text(result)}", 0, 1)
                except ValueError:
                    pdf.set_text_color(0, 0, 0)
                    pdf.set_font("Arial", '', 10)
                    pdf.cell(0, 8, sanitize_text(feature), 0, 1)
            else:
                pdf.set_text_color(0, 0, 0)
                pdf.set_font("Arial", '', 10)
                pdf.cell(0, 8, sanitize_text(feature), 0, 1)
        pdf.ln(10)

    # --- SENSOR BREAKDOWN ---
    pdf.chapter_title("1", "AI META-CLASSIFIER SENSOR BREAKDOWN")
    pdf.draw_table_row("Neural Network (EfficientNet-B4) Confidence", fmt_pct(result_data.get('nn_score'), '.2f'), pdf.gray_bg, True)
    pdf.draw_table_row("Frequency Domain Anomaly", fmt_pct(result_data.get('spectral_anomaly_score'), '.2f'), None, True)
    pdf.draw_table_row("Error Level Analysis (ELA) Compression", fmt_pct(result_data.get('ela_score'), '.2f'), pdf.gray_bg, True)
    pdf.draw_table_row("Biological Geometry Anomaly", fmt_pct(result_data.get('geometry_anomaly_score'), '.2f'), None, True)
    pdf.draw_table_row("Sensor Noise Fingerprint (PRNU)", fmt_pct(result_data.get('noise_score'), '.2f'), pdf.gray_bg, True)
    pdf.draw_table_row("Chrominance Color Space Anomaly", fmt_pct(result_data.get('color_score'), '.2f'), None, True)
    if 'sync_score' in result_data:
        pdf.draw_table_row("Audio-Visual Desynchronization", fmt_pct(result_data.get('sync_score'), '.2f'), pdf.gray_bg, True)
    if result_data.get('eye_score') is not None and float(result_data.get('eye_score') or 0) > 0:
        pdf.draw_table_row("Eye & Gaze Anomaly", fmt_pct(result_data.get('eye_score'), '.2f'), None, True)
    if result_data.get('voice_score') is not None and float(result_data.get('voice_score') or 0) > 0:
        pdf.draw_table_row("Voice Spoofing Analysis", fmt_pct(result_data.get('voice_score'), '.2f'), pdf.gray_bg, True)
    if result_data.get('flow_score') is not None and float(result_data.get('flow_score') or 0) > 0:
        pdf.draw_table_row("Temporal Optical Flow Jitter", fmt_pct(result_data.get('flow_score'), '.2f'), None, True)
    if 'metadata_score' in result_data:
        pdf.draw_table_row("Metadata & EXIF Integrity", fmt_pct(result_data.get('metadata_score'), '.2f'), pdf.gray_bg, True)
    if result_data.get('lighting_score') is not None and float(result_data.get('lighting_score') or 0) > 0:
        pdf.draw_table_row("3D Lighting Consistency", fmt_pct(result_data.get('lighting_score'), '.2f'), None, True)
    if result_data.get('cfa_score') is not None and float(result_data.get('cfa_score') or 0) > 0:
        pdf.draw_table_row("CFA Artifacts Analysis", fmt_pct(result_data.get('cfa_score'), '.2f'), pdf.gray_bg, True)
    if result_data.get('corneal_score') is not None and float(result_data.get('corneal_score') or 0) > 0:
        pdf.draw_table_row("Corneal Reflection Consistency", fmt_pct(result_data.get('corneal_score'), '.2f'), None, True)
    if result_data.get('rppg_score') is not None and float(result_data.get('rppg_score') or 0) > 0:
        pdf.draw_table_row("Remote Photoplethysmography (rPPG)", fmt_pct(result_data.get('rppg_score'), '.2f'), pdf.gray_bg, True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(120, 10, "  FINAL AI CONFIDENCE SCORE", 'B', 0, 'L', fill=True)
    pdf.set_text_color(*verdict_color)
    pdf.cell(0, 10, fmt_pct(score, '.2f'), 'B', 1, 'R', fill=True)
    pdf.set_text_color(0, 0, 0)
    
    # Visual gauge bar
    pdf.set_fill_color(230, 230, 230)
    pdf.rect(10, pdf.get_y() + 2, 190, 4, 'F')
    pdf.set_fill_color(*verdict_color)
    pdf.rect(10, pdf.get_y() + 2, max(min(190 * score, 190), 2), 4, 'F')
    
    pdf.ln(10)

    # --- ADVANCED MODULES ---
    pdf.chapter_title("2", "FREQUENCY & COMPRESSION ANALYSIS")
    freq = result_data.get('frequency_analysis', {}) or {}
    pdf.draw_table_row("Spectral Anomaly Score", fmt_pct(freq.get('spectral_anomaly_score'), '.1f'), pdf.gray_bg)
    pdf.draw_table_row("High-Frequency Energy Ratio", fmt_pct(freq.get('high_freq_energy_ratio'), '.4f'))
    if 'dct_hf_ratio' in freq:
        pdf.draw_table_row("DCT HF Energy Ratio", fmt_pct(freq.get('dct_hf_ratio'), '.4f'), pdf.gray_bg)
    if 'channel_variance' in freq:
        pdf.draw_table_row("Cross-Channel Variance", fmt_num(freq.get('channel_variance'), '.4f'))
    if 'pca_variance_ratio' in freq:
        pdf.draw_table_row("PCA (PC3) Variance Ratio", fmt_pct(freq.get('pca_variance_ratio'), '.4f'), pdf.gray_bg)
    if 'swn_anomaly_ratio' in freq:
        pdf.draw_table_row("SWN Anomaly Ratio", fmt_pct(freq.get('swn_anomaly_ratio'), '.2f'))
    if 'hpf_variance' in freq:
        pdf.draw_table_row("HPF Variance", fmt_num(freq.get('hpf_variance'), '.1f'), pdf.gray_bg)
    if 'cepstrum_var' in freq:
        pdf.draw_table_row("Cepstrum Variance", fmt_num(freq.get('cepstrum_var'), '.6f'))
    if 'dwt_var' in freq:
        pdf.draw_table_row("DWT Diagonal Variance", fmt_num(freq.get('dwt_var'), '.2f'), pdf.gray_bg)

    ela = result_data.get('ela_analysis', {}) or {}
    if 'ela_smooth_anomaly' in ela:
        pdf.draw_table_row("Edge-Aware Smooth Region Anomaly", fmt_pct(ela.get('ela_smooth_anomaly'), '.2f'), pdf.gray_bg)
    if 'ela_base_variance' in ela:
        pdf.draw_table_row("Base ELA Variance", fmt_pct(ela.get('ela_base_variance'), '.2f'))
    pdf.ln(2)
    pdf.set_font("Arial", 'I', 9)
    pdf.multi_cell(0, 5, "Analysis: " + sanitize_text(ela.get('ela_interpretation', 'N/A')))
    pdf.ln(5)

    # --- GEOMETRY ---
    pdf.chapter_title("3", "BIOLOGICAL & FACIAL GEOMETRY")
    face = result_data.get('face_geometry', {}) or {}
    if face.get('face_detected'):
        pdf.draw_table_row("Geometry Anomaly Score", fmt_pct(face.get('geometry_anomaly_score'), '.1f'), pdf.gray_bg)
        if 'temporal_jitter_score' in face:
            pdf.draw_table_row("Temporal Geometric Jitter", fmt_pct(face.get('temporal_jitter_score'), '.1f'))
        if 'golden_ratio' in face:
            pdf.draw_table_row("Biological Golden Ratio", fmt_num(face.get('golden_ratio'), '.3f'), pdf.gray_bg)
        if 'interocular_ratio' in face:
            pdf.draw_table_row("Interocular Proportion", fmt_num(face.get('interocular_ratio'), '.3f'))
        if 'symmetry_score' in face:
            pdf.draw_table_row("Facial Symmetry Deviation", fmt_pct(face.get('symmetry_score'), '.1f'), pdf.gray_bg)
        pdf.ln(2)
        pdf.set_font("Arial", 'I', 9)
        pdf.multi_cell(0, 5, "Analysis: " + sanitize_text(face.get('face_geometry_interpretation', '')))
    else:
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 8, "No face detected in the analyzed frame.", 0, 1)

    eye = result_data.get('eye_analysis', {}) or {}
    if eye:
        pdf.ln(5)
        pdf.draw_table_row("Eye & Gaze Anomaly Score", fmt_pct(eye.get('eye_anomaly_score'), '.1f'), pdf.gray_bg)
        if 'blink_rate_per_min' in eye:
            pdf.draw_table_row("Blink Rate (BPM)", fmt_num(eye.get('blink_rate_per_min'), '.1f'))
        if 'gaze_asymmetry' in eye:
            pdf.draw_table_row("Gaze Asymmetry", fmt_num(eye.get('gaze_asymmetry'), '.3f'), pdf.gray_bg)
        if eye.get('warnings'):
            pdf.ln(2)
            pdf.set_font("Arial", 'I', 9)
            pdf.multi_cell(0, 5, "Warnings: " + sanitize_text("; ".join(eye.get('warnings'))))
    
    flow = result_data.get('flow_analysis', {}) or {}
    if flow:
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 8, "Temporal Consistency (Optical Flow)", 0, 1)
        pdf.draw_table_row("Optical Flow Jitter Score", fmt_pct(flow.get('flow_anomaly_score'), '.1f'), pdf.gray_bg)
        if 'mean_motion_variance' in flow:
            pdf.draw_table_row("Mean Motion Variance", fmt_num(flow.get('mean_motion_variance'), '.3f'))
        if flow.get('warnings'):
            pdf.ln(2)
            pdf.set_font("Arial", 'I', 9)
            pdf.multi_cell(0, 5, "Warnings: " + sanitize_text("; ".join(flow.get('warnings'))))
    
    # --- NOISE & COLOR ---
    pdf.chapter_title("4", "SENSOR NOISE & COLOR SPACE")
    noise = result_data.get('noise_analysis', {}) or {}
    pdf.draw_table_row("PRNU Noise Anomaly Score", fmt_pct(noise.get('noise_score'), '.1f'), pdf.gray_bg)
    if 'prnu_variance' in noise:
        pdf.draw_table_row("PRNU Variance", fmt_num(noise.get('prnu_variance'), '.4f'))
        
    color = result_data.get('color_analysis', {}) or {}
    if color:
        pdf.draw_table_row("Chrominance Anomaly Score", fmt_pct(color.get('color_anomaly_score'), '.1f'), pdf.gray_bg)
        if 'cb_variance' in color:
            pdf.draw_table_row("Cb Channel Variance", fmt_num(color.get('cb_variance'), '.2f'))
        if 'cr_variance' in color:
            pdf.draw_table_row("Cr Channel Variance", fmt_num(color.get('cr_variance'), '.2f'), pdf.gray_bg)
        if 's_variance' in color:
            pdf.draw_table_row("HSV Saturation Variance", fmt_num(color.get('s_variance'), '.2f'))
        if 'a_variance' in color:
            pdf.draw_table_row("LAB a* Channel Variance", fmt_num(color.get('a_variance'), '.2f'), pdf.gray_bg)

    # --- ADVANCED PHYSICS (LIGHTING, CFA, CORNEAL) ---
    lighting = result_data.get('lighting_analysis', {}) or {}
    cfa = result_data.get('cfa_analysis', {}) or {}
    corneal = result_data.get('corneal_analysis', {}) or {}
    
    if lighting or cfa or corneal:
        pdf.chapter_title("5", "PHYSICAL OPTICS & SENSOR ARTIFACTS")
        if lighting:
            pdf.draw_table_row("Lighting Anomaly Score", fmt_pct(lighting.get('lighting_anomaly_score'), '.1f'), pdf.gray_bg)
        if cfa:
            pdf.draw_table_row("CFA Anomaly Score", fmt_pct(cfa.get('cfa_score'), '.1f'))
        if corneal:
            pdf.draw_table_row("Corneal Reflection Anomaly", fmt_pct(corneal.get('corneal_score'), '.1f'), pdf.gray_bg)
        pdf.ln(5)

    # --- AUDIO SYNC & PHYSIOLOGY ---
    sync = result_data.get('sync_analysis', {}) or {}
    voice = result_data.get('voice_analysis', {}) or {}
    rppg = result_data.get('rppg_analysis', {}) or {}
    if sync or voice or rppg:
        pdf.chapter_title("6", "AUDIO FORENSICS & PHYSIOLOGY")
        if sync:
            pdf.draw_table_row("Pearson Correlation", fmt_num(sync.get('correlation'), '.3f'), pdf.gray_bg)
            if 'lse_c' in sync:
                pdf.draw_table_row("LSE-C (Expert Confidence)", fmt_num(sync.get('lse_c'), '.2f'))
            if 'lse_d' in sync:
                pdf.draw_table_row("LSE-D (Expert Distance)", fmt_num(sync.get('lse_d'), '.2f'), pdf.gray_bg)
            pdf.ln(2)
            pdf.set_font("Arial", 'I', 9)
            pdf.multi_cell(0, 5, "Sync Analysis: Mathematical correlation between visual Mouth Aspect Ratio (MAR) and Audio MFCC. Low confidence indicates phonetic dubbing.")
        
        if voice:
            pdf.ln(5)
            pdf.draw_table_row("Voice Spoofing Score", fmt_pct(voice.get('voice_anomaly_score'), '.1f'), pdf.gray_bg)
            if 'high_freq_ratio' in voice:
                pdf.draw_table_row("High Freq Ratio", fmt_num(voice.get('high_freq_ratio'), '.4f'))
            if 'zcr_variance' in voice:
                pdf.draw_table_row("Zero-Crossing Variance", fmt_num(voice.get('zcr_variance'), '.5f'), pdf.gray_bg)
            if voice.get('warnings'):
                pdf.ln(2)
                pdf.set_font("Arial", 'I', 9)
                pdf.multi_cell(0, 5, "Voice Warnings: " + sanitize_text("; ".join(voice.get('warnings'))))
                
        if rppg:
            pdf.ln(5)
            pdf.draw_table_row("rPPG Heart Rate Anomaly", fmt_pct(rppg.get('rppg_anomaly_score'), '.1f'), pdf.gray_bg)
            if 'snr' in rppg:
                pdf.draw_table_row("Signal-to-Noise Ratio (SNR)", f"{fmt_num(rppg.get('snr'), '.2f')} dB")
            if 'bpm' in rppg:
                pdf.draw_table_row("Estimated BPM", fmt_num(rppg.get('bpm'), '.1f'), pdf.gray_bg)

    # --- METADATA ---
    metadata = result_data.get('metadata_analysis', {}) or {}
    if metadata:
        pdf.chapter_title("7", "METADATA & EXIF INTEGRITY")
        pdf.draw_table_row("Metadata Anomaly Score", fmt_pct(metadata.get('metadata_anomaly_score'), '.1f'), pdf.gray_bg)
        if 'missing_tags' in metadata and len(metadata['missing_tags']) > 0:
            pdf.draw_table_row("Missing Standard Tags", f"{len(metadata['missing_tags'])}")
        if 'software_signature' in metadata and metadata['software_signature']:
            pdf.draw_table_row("Software Signature", f"{str(metadata['software_signature'])[:30]}", pdf.gray_bg)

    # --- VISUAL EVIDENCE ---
    pdf.add_page()
    pdf.chapter_title("8", "VISUAL EVIDENCE GALLERY")
    pdf.ln(2)

    exhibit_counter = 1
    col_index = 0
    max_row_h = 0
    pdf.current_row_y = pdf.get_y()

    def embed_image(title, img_path):
        nonlocal exhibit_counter, col_index, max_row_h
        if not img_path or not isinstance(img_path, str):
            return

        resolved_path = img_path
        if not os.path.exists(resolved_path):
            candidates = [
                img_path.lstrip("/\\"),
                os.path.join("uploads", os.path.basename(img_path)),
                os.path.join("backend", img_path.lstrip("/\\")),
                os.path.join("backend", "uploads", os.path.basename(img_path)),
                os.path.join("..", img_path.lstrip("/\\"))
            ]
            for cand in candidates:
                if os.path.exists(cand):
                    resolved_path = cand
                    break

        if resolved_path and os.path.exists(resolved_path):
            try:
                img = cv2.imread(resolved_path)
                if img is not None:
                    h, w, _ = img.shape
                    aspect_ratio = h / w
                    target_w = 90
                    target_h = target_w * aspect_ratio
                    
                    if col_index == 0:
                        if pdf.get_y() + target_h + 20 > 270:
                            pdf.add_page()
                            pdf.current_row_y = pdf.get_y()
                        x_pos = 10
                        max_row_h = target_h
                    else:
                        x_pos = 110
                        max_row_h = max(max_row_h, target_h)
                    
                    y_pos = pdf.current_row_y
                    
                    # Draw subtle border
                    pdf.set_draw_color(200, 200, 200)
                    pdf.rect(x_pos - 1, y_pos - 1, target_w + 2, target_h + 2)
                    
                    pdf.image(resolved_path, x=x_pos, y=y_pos, w=target_w)
                    
                    # Caption
                    pdf.set_xy(x_pos, y_pos + target_h + 2)
                    pdf.set_font("Arial", 'B', 8)
                    pdf.set_text_color(*pdf.brand_color)
                    pdf.cell(target_w, 5, f"EXHIBIT {exhibit_counter}: {title}", 0, 0, 'C')
                    pdf.set_text_color(0, 0, 0)
                    
                    exhibit_counter += 1
                    col_index += 1
                    
                    if col_index == 2:
                        pdf.set_y(pdf.current_row_y + max_row_h + 15)
                        col_index = 0
                        pdf.current_row_y = pdf.get_y()
                else:
                    pdf.set_y(pdf.current_row_y + max_row_h + 15)
                    pdf.set_font("Arial", 'I', 10)
                    pdf.cell(0, 6, f"(Exhibit {exhibit_counter}: {title} - Image file corrupt)", 0, 1, 'C')
                    col_index = 0
                    pdf.current_row_y = pdf.get_y()
            except Exception as e:
                pdf.set_y(pdf.current_row_y + max_row_h + 15)
                pdf.cell(0, 6, f"(Error embedding image: {str(e)})", 0, 1, 'C')
                col_index = 0
                pdf.current_row_y = pdf.get_y()

    def gallery_section(title_text):
        nonlocal col_index, max_row_h
        if col_index != 0:
            pdf.set_y(pdf.current_row_y + max_row_h + 15)
            col_index = 0
            pdf.current_row_y = pdf.get_y()
        
        if pdf.get_y() > 250:
            pdf.add_page()
            
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, title_text.upper(), 'B', 1, 'L')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        pdf.current_row_y = pdf.get_y()

    # Group 1: High Level
    face_crop = result_data.get('face_crop_path')
    heatmaps = result_data.get('heatmaps', []) or []
    if face_crop or heatmaps or ela.get('ela_heatmap_path'):
        gallery_section("Neural Attention & Face Crop")
        
    if face_crop:
        embed_image("Original Face Crop (Input)", face_crop)
    if heatmaps:
        embed_image("GradCAM Neural Attention Heatmap", heatmaps[0])
        if len(heatmaps) > 1:
            embed_image("High-Resolution Guided Grad-CAM", heatmaps[1])
    if ela.get('ela_heatmap_path'):
        embed_image("Error Level Analysis (ELA) Overlay", ela.get('ela_heatmap_path'))
    if ela.get('ela_image_path'):
        embed_image("Base ELA Map", ela.get('ela_image_path'))
    if ela.get('ghosting_path'):
        embed_image("JPEG Ghosting Analysis", ela.get('ghosting_path'))
    if ela.get('hsv_ela_path'):
        embed_image("HSV Color ELA", ela.get('hsv_ela_path'))

    # Group 2: Frequency
    freq_items = [freq.get(k) for k in ['fft_magnitude_path', 'dct_spectrum_path', 'block_dct_path', 'high_pass_path', 'swn_noise_path', 'phase_spectrum_path', 'saliency_map_path', 'pca_spectrum_path', 'cepstrum_path', 'dwt_diagonal_path']]
    if any(freq_items):
        gallery_section("Frequency Domain Analysis")

    if freq.get('fft_magnitude_path'):
        embed_image("FFT Magnitude Spectrum", freq.get('fft_magnitude_path'))
    if freq.get('dct_spectrum_path'):
        embed_image("DCT Frequency Spectrum", freq.get('dct_spectrum_path'))
    if freq.get('block_dct_path'):
        embed_image("Block DCT Artifact Analysis", freq.get('block_dct_path'))
    if freq.get('high_pass_path'):
        embed_image("High-Pass Spatial Filter", freq.get('high_pass_path'))
    if freq.get('swn_noise_path'):
        embed_image("Switching Noise (SWN) Map", freq.get('swn_noise_path'))
    if freq.get('phase_spectrum_path'):
        embed_image("Structural Phase Spectrum", freq.get('phase_spectrum_path'))
    if freq.get('saliency_map_path'):
        embed_image("Spectral Residual Saliency (GAN Checkerboard)", freq.get('saliency_map_path'))
    if freq.get('pca_spectrum_path'):
        embed_image("PCA Spectral Component", freq.get('pca_spectrum_path'))
    if freq.get('cepstrum_path'):
        embed_image("Cepstrum Analysis", freq.get('cepstrum_path'))
    if freq.get('dwt_diagonal_path'):
        embed_image("Discrete Wavelet Transform (DWT)", freq.get('dwt_diagonal_path'))

    # Group 3: Face
    face_items = [face.get(k) for k in ['radar_chart_path', 'landmark_visualization_path', 'head_pose_visualization_path', 'symmetry_map_path', 'temporal_jitter_plot_path', 'texture_map_path']]
    if any(face_items):
        gallery_section("Facial Geometry & Texture")
        
    if face.get('radar_chart_path'):
        embed_image("Face Geometry Radar Chart", face.get('radar_chart_path'))
    if face.get('landmark_visualization_path'):
        embed_image("Facial Landmark Mapping", face.get('landmark_visualization_path'))
    if face.get('head_pose_visualization_path'):
        embed_image("3D Head Pose", face.get('head_pose_visualization_path'))
    if face.get('symmetry_map_path'):
        embed_image("Facial Symmetry Deformation", face.get('symmetry_map_path'))
    if face.get('temporal_jitter_plot_path'):
        embed_image("Temporal Geometric Jitter", face.get('temporal_jitter_plot_path'))
    if face.get('texture_map_path'):
        embed_image("Face Texture Anomaly", face.get('texture_map_path'))

    # Group 4: Noise & Color
    noise_items = [noise.get(k) for k in ['denoised_map_path', 'noise_map_path', 'srm_map_path']]
    color_items = [color.get(k) for k in ['cb_map_path', 'cr_map_path', 's_map_path', 'a_map_path']]
    if any(noise_items) or any(color_items):
        gallery_section("Noise Residuals & Chrominance")
        
    if noise.get('denoised_map_path'):
        embed_image("Denoised Image", noise.get('denoised_map_path'))
    if noise.get('noise_map_path'):
        embed_image("Noise Residual Map", noise.get('noise_map_path'))
    if noise.get('srm_map_path'):
        embed_image("Spatial Rich Model (SRM) Filter", noise.get('srm_map_path'))
    if color.get('cb_map_path'):
        embed_image("Chrominance (Cb) Map", color.get('cb_map_path'))
    if color.get('cr_map_path'):
        embed_image("Chrominance (Cr) Map", color.get('cr_map_path'))
    if color.get('s_map_path'):
        embed_image("Saturation Channel Map", color.get('s_map_path'))
    if color.get('a_map_path'):
        embed_image("LAB (a*) Channel Map", color.get('a_map_path'))

    # Group 5: Temporal & Audio
    temporal_items = [sync.get('sync_plot_path'), result_data.get('eye_analysis', {}).get('eye_plot_path'), result_data.get('voice_analysis', {}).get('voice_plot_path'), result_data.get('flow_analysis', {}).get('flow_plot_path')]
    if any(temporal_items):
        gallery_section("Temporal, Audio & Motion")
        
    if sync.get('sync_plot_path'):
        embed_image("Audio-Visual Synchronization (MFCC vs MAR)", sync.get('sync_plot_path'))
    
    eye = result_data.get('eye_analysis', {})
    if eye.get('eye_plot_path'):
        embed_image("Eye Aspect Ratio (EAR) Tracker", eye.get('eye_plot_path'))
        
    voice = result_data.get('voice_analysis', {})
    if voice.get('voice_plot_path'):
        embed_image("Mel-Frequency Spectrogram (Voice Spoofing)", voice.get('voice_plot_path'))
        
    flow = result_data.get('flow_analysis', {})
    if flow.get('flow_plot_path'):
        embed_image("Temporal Motion Variance", flow.get('flow_plot_path'))
    if flow.get('flow_field_path'):
        embed_image("Optical Flow HSV Field", flow.get('flow_field_path'))
        
    lighting = result_data.get('lighting_analysis', {})
    cfa = result_data.get('cfa_analysis', {})
    corneal = result_data.get('corneal_analysis', {})
    rppg = result_data.get('rppg_analysis', {})
    
    advanced_items = [lighting.get('lighting_map_path'), cfa.get('cfa_map_path'), corneal.get('corneal_map_path'), rppg.get('rppg_plot_path')]
    if any(advanced_items):
        gallery_section("Advanced Modalities")

    if lighting.get('lighting_map_path'):
        embed_image("3D Lighting Consistency Map", lighting.get('lighting_map_path'))
        
    if cfa.get('cfa_map_path'):
        embed_image("CFA Artifacts Map", cfa.get('cfa_map_path'))
        
    corneal = result_data.get('corneal_analysis', {})
    if corneal.get('corneal_map_path'):
        embed_image("Corneal Reflection Overlay", corneal.get('corneal_map_path'))
        
    rppg = result_data.get('rppg_analysis', {})
    if rppg.get('rppg_plot_path'):
        embed_image("rPPG Heartbeat Waveform", rppg.get('rppg_plot_path'))
    if rppg.get('rppg_map_path'):
        embed_image("rPPG Face ROI Heatmap", rppg.get('rppg_map_path'))

    # --- DISCLAIMER ---
    if pdf.get_y() > 250:
        pdf.add_page()
    pdf.ln(10)
    pdf.set_fill_color(250, 240, 240)
    pdf.set_draw_color(*pdf.danger_color)
    pdf.rect(10, pdf.get_y(), 190, 25, 'FD')
    
    pdf.set_font("Arial", 'B', 9)
    pdf.set_text_color(*pdf.danger_color)
    pdf.set_xy(12, pdf.get_y() + 2)
    pdf.cell(0, 5, "LEGAL DISCLAIMER", 0, 1)
    
    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(0, 0, 0)
    pdf.set_x(12)
    pdf.multi_cell(186, 4, "This report is generated by an automated Artificial Intelligence meta-classifier system. It should be reviewed and validated by a qualified digital forensic analyst before being admitted as evidence in legal or disciplinary proceedings. The meta-classifier synthesizes multiple independent detection vectors, but false positives and false negatives remain theoretically possible.")

    pdf.output(output_path)
    return output_path
